version: "3.8"
services:
    alpine:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: comercio-admin
        restart: on-failure
        ports:
            - "1234:80"
        volumes:
            - ./conf/site.conf:/etc/nginx/http.d/default.conf
            - ./comercio-app:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: mysqlpass
        networks:
            - acpLaravel

    db:
        image: mariadb:10.8.2
        container_name: comercio-db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysqlpass
        networks:
            - acpLaravel

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: comercio-pma
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            PMA_PASSWORD: mypmapass
        depends_on:
            - db
        networks:
            - acpLaravel

volumes:
    db-data:

networks:
    acpLaravel: