<link rel="stylesheet" href="{{ asset('frontend/assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/owl.theme.default.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/jquery.bxslider.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/rating.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/spacing.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/bootstrap-touch-slider.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/tree-menu.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/main.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/responsive.css') }}">
